/*
 This file was autogenerated via
 --------------------------------------------------------------
 ldetool generate --go-string source/gitlab/major_extractor.lde
 --------------------------------------------------------------
 do not touch it with bare hands!
*/

package gitlab

import (
	"fmt"
	"strconv"
	"strings"
)

// majorExtractor ...
type majorExtractor struct {
	Rest  string
	Major int
}

func (p *majorExtractor) extract(line string) (bool, error) {
	p.Rest = line
	var err error
	var pos int
	var tmp string
	var tmpInt int64

	// Checks if the rest starts with 'v' and pass it
	if len(p.Rest) >= 1 && p.Rest[0] == 'v' {
		p.Rest = p.Rest[1:]
	} else {
		return false, nil
	}

	// Take until '.' as majorExtractor(int)
	pos = strings.IndexByte(p.Rest, '.')
	if pos >= 0 {
		tmp = p.Rest[:pos]
		p.Rest = p.Rest[pos+1:]
	} else {
		return false, nil
	}
	if tmpInt, err = strconv.ParseInt(tmp, 10, 64); err != nil {
		return false, fmt.Errorf("Cannot parse `%s`: %s", string(tmp), err)
	}
	p.Major = int(tmpInt)

	return true, nil
}
