/*
 This file was autogenerated via
 ----------------------------------------
 ldetool generate --go-string version.lde
 ----------------------------------------
 do not touch it with bare hands!
*/

package gitlab

import (
	"strconv"

	"github.com/sirkon/goproxy/internal/errors"
)

// pathVersionExtractor ...
type pathVersionExtractor struct {
	Rest    string
	Version int
}

// Extract ...
func (p *pathVersionExtractor) Extract(line string) (bool, error) {
	p.Rest = line
	var err error
	var tmpInt int64

	// Checks if the rest starts with 'v' and pass it
	if len(p.Rest) >= 1 && p.Rest[0] == 'v' {
		p.Rest = p.Rest[1:]
	} else {
		return false, nil
	}

	// Take the rest as Version(int)
	if tmpInt, err = strconv.ParseInt(p.Rest, 10, 64); err != nil {
		return false, errors.Wrapf(err, "parsing `%s` into field Version(int)", p.Rest)
	}
	p.Version = int(tmpInt)
	p.Rest = p.Rest[len(p.Rest):]
	return true, nil
}
