
/*
 This file was autogenerated via
 ------------------------------------------------
 ldetool generate --go-string major_extractor.lde
 ------------------------------------------------
 do not touch it with bare hands!
*/

package fsrepack

import (
	"fmt"
	"strconv"
)

// MajorExtractor ...
type MajorExtractor struct {
	Rest  string
	Major int
}

// Extract ...
func (p *MajorExtractor) Extract(line string) (bool, error) {
	p.Rest = line
	var err error
	var pos int
	var tmp string
	var tmpInt int64

	// Checks if the rest starts with 'v' and pass it
	if len(p.Rest) >= 1 && p.Rest[0] == 'v' {
		p.Rest = p.Rest[1:]
	} else {
		return false, nil
	}

	// Take until '.' as Major(int)
	pos = -1
	for i, char := range p.Rest {
		if char == '.' {
			pos = i
			break
		}
	}
	if pos >= 0 {
		tmp = p.Rest[:pos]
		p.Rest = p.Rest[pos+1:]
	} else {
		return false, nil
	}
	if tmpInt, err = strconv.ParseInt(tmp, 10, 64); err != nil {
		return false, fmt.Errorf("cannot parse `%s` into field Major(int): %s", tmp, err)
	}
	p.Major = int(tmpInt)

	return true, nil
}
