
/*
 This file was autogenerated via
 ---------------------------------------------------------------------------------
 ldetool generate --go-string --package extraction internal/mod_info_extractor.lde
 ---------------------------------------------------------------------------------
 do not touch it with bare hands!
*/

package extraction

import (
	"strings"
)

var slashDogVSlash = "/@v/"

// ModInfoExtractor ...
type ModInfoExtractor struct {
	Rest   string
	Module string
	Suffix string
}

// Extract ...
func (p *ModInfoExtractor) Extract(line string) (bool, error) {
	p.Rest = line
	var pos int

	// Checks if the rest starts with '/' and pass it
	if len(p.Rest) >= 1 && p.Rest[0] == '/' {
		p.Rest = p.Rest[1:]
	} else {
		return false, nil
	}

	// Take until "/@v/" as Module(string)
	pos = strings.Index(p.Rest, slashDogVSlash)
	if pos >= 0 {
		p.Module = p.Rest[:pos]
		p.Rest = p.Rest[pos+len(slashDogVSlash):]
	} else {
		return false, nil
	}

	// Take the rest as Suffix(string)
	p.Suffix = p.Rest
	p.Rest = p.Rest[len(p.Rest):]
	return true, nil
}
